name: PRB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pr:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v3.5.3

      - uses: actions/setup-node@v3.5.0
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
